In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [2]:
df = pd.read_csv('../data/raw/neo_close_approaches_raw.csv')

In [3]:
df.head()

,des,orbit_id,jd,cd,dist,dist_min,dist_max,v_rel,v_inf,t_sigma_f,h,diameter,diameter_sigma,fullname
0,509352,64,2.415024e+06,1900-Jan-04 22:25,0.009632,0.009625,0.009639,8.686710,8.654806,00:02,20.14,NaN,NaN,509352 (2007 AG)
1,2014 SC324,57,2.415031e+06,1900-Jan-11 01:07,0.039964,0.039904,0.040025,10.652382,10.646122,00:18,24.39,NaN,NaN,(2014 SC324)
2,2012 UK171,54,2.415032e+06,1900-Jan-12 23:02,0.049706,0.049578,0.049834,7.153496,7.145999,00:05,24.46,NaN,NaN,(2012 UK171)
3,2024 BA5,3,2.415045e+06,1900-Jan-25 06:22,0.026434,0.011310,0.198644,8.436204,8.424247,21:33,26.02,NaN,NaN,(2024 BA5)
4,2024 BW1,6,2.415045e+06,1900-Jan-25 19:29,0.037979,0.010125,0.089436,6.339787,6.328711,4_11:16,25.12,NaN,NaN,(2024 BW1)

In [4]:
print(df.shape)
print(df.dtypes)
print(df.isnull().sum())

(51122, 14)
des                   str
orbit_id              str
jd                float64
cd                    str
dist              float64
dist_min          float64
dist_max          float64
v_rel             float64
v_inf             float64
t_sigma_f             str
h                 float64
diameter          float64
diameter_sigma    float64
fullname              str
dtype: object
des                   0
orbit_id              0
jd                    0
cd                    0
dist                  0
dist_min              0
dist_max              0
v_rel                 0
v_inf                25
t_sigma_f             0
h                    10
diameter          49634
diameter_sigma    49785
fullname              0
dtype: int64

### Seeing if its better to drop v_inf column or not

In [6]:
df[df['v_inf'].isna()]

,des,orbit_id,jd,cd,dist,dist_min,dist_max,v_rel,v_inf,t_sigma_f,h,diameter,diameter_sigma,fullname
7696,2012 TF79,18,2.439511e+06,1967-Jan-20 03:00,0.035501,0.035019,0.036000,0.275869,NaN,4_00:34,27.38,NaN,NaN,(2012 TF79)
13794,2006 RH120,54,2.453990e+06,2006-Sep-11 07:40,0.005611,0.005611,0.005611,0.862033,NaN,< 00:01,29.50,NaN,NaN,(2006 RH120)
13904,2006 RH120,54,2.454104e+06,2007-Jan-03 18:02,0.003566,0.003566,0.003566,1.038185,NaN,< 00:01,29.50,NaN,NaN,(2006 RH120)
13979,2006 RH120,54,2.454185e+06,2007-Mar-25 12:32,0.002363,0.002363,0.002363,1.366048,NaN,< 00:01,29.50,NaN,NaN,(2006 RH120)
14028,2006 RH120,54,2.454266e+06,2007-Jun-14 05:31,0.001851,0.001851,0.001851,1.570519,NaN,< 00:01,29.50,NaN,NaN,(2006 RH120)
19194,2020 CD3,27,2.458015e+06,2017-Sep-18 06:00,0.001339,0.001339,0.001339,1.887389,NaN,< 00:01,31.74,NaN,NaN,(2020 CD3)
19522,2020 CD3,27,2.458094e+06,2017-Dec-06 09:22,0.001662,0.001662,0.001662,1.666995,NaN,< 00:01,31.74,NaN,NaN,(2020 CD3)
19742,2020 CD3,27,2.458169e+06,2018-Feb-19 08:28,0.001489,0.001489,0.001489,1.773529,NaN,< 00:01,31.74,NaN,NaN,(2020 CD3)
19962,2020 CD3,27,2.458248e+06,2018-May-09 13:48,0.000172,0.000172,0.000172,5.530533,NaN,< 00:01,31.74,NaN,NaN,(2020 CD3)
20122,2020 CD3,27,2.458340e+06,2018-Aug-09 12:37,0.002042,0.002042,0.002042,1.475608,NaN,< 00:01,31.74,NaN,NaN,(2020 CD3)
20352,2020 CD3,27,2.458418e+06,2018-Oct-26 00:10,0.002152,0.002151,0.002152,1.445736,NaN,< 00:01,31.74,NaN,NaN,(2020 CD3)
20611,2020 CD3,27,2.458500e+06,2019-Jan-16 17:12,0.001084,0.001084,0.001084,2.133939,NaN,< 00:01,31.74,NaN,NaN,(2020 CD3)
20868,2020 CD3,27,2.458578e+06,2019-Apr-04 09:33,0.000088,0.000088,0.000088,7.773726,NaN,< 00:01,31.74,NaN,NaN,(2020 CD3)
21113,2020 CD3,27,2.458665e+06,2019-Jun-30 17:27,0.001851,0.001851,0.001851,1.556385,NaN,< 00:01,31.74,NaN,NaN,(2020 CD3)
21274,2020 CD3,27,2.458737e+06,2019-Sep-10 04:00,0.002019,0.002019,0.002019,1.471723,NaN,< 00:01,31.74,NaN,NaN,(2020 CD3)
21642,2020 CD3,27,2.458806e+06,2019-Nov-18 13:04,0.001936,0.001936,0.001936,1.540772,NaN,< 00:01,31.74,NaN,NaN,(2020 CD3)
22006,2020 CD3,27,2.458893e+06,2020-Feb-13 16:20,0.000315,0.000315,0.000315,4.073914,NaN,< 00:01,31.74,NaN,NaN,(2020 CD3)
25708,2022 NX1,15,2.459757e+06,2022-Jun-26 20:23,0.005429,0.005429,0.005429,0.958740,NaN,< 00:01,28.07,NaN,NaN,(2022 NX1)
33100,2006 RH120,54,2.462002e+06,2028-Aug-18 04:47,0.026936,0.026073,0.027858,0.138271,NaN,4_11:58,29.50,NaN,NaN,(2006 RH120)
35158,2020 CD3,27,2.467695e+06,2044-Mar-20 10:43,0.024444,0.024441,0.024447,0.216288,NaN,00:36,31.74,NaN,NaN,(2020 CD3)
37470,2023 HG11,4,2.474035e+06,2061-Jul-29 16:21,0.032892,0.032366,0.033813,0.073451,NaN,2_10:47,28.37,NaN,NaN,(2023 HG11)
37482,2020 CD3,27,2.474057e+06,2061-Aug-20 04:39,0.033245,0.032890,0.033602,0.383207,NaN,13:21,31.74,NaN,NaN,(2020 CD3)
45280,2024 GB15,7,2.496225e+06,2122-May-01 19:15,0.044388,0.044387,0.044388,0.322089,NaN,00:02,26.95,NaN,NaN,(2024 GB15)
49237,2024 GB15,7,2.514119e+06,2171-Apr-28 00:52,0.044198,0.044198,0.044198,0.324525,NaN,< 00:01,26.95,NaN,NaN,(2024 GB15)
49829,2024 GB15,7,2.517064e+06,2179-May-21 04:34,0.047423,0.047421,0.047425,0.168685,NaN,00:06,26.95,NaN,NaN,(2024 GB15)

### Seeing if its better to drop h column or not

In [7]:
df[df['h'].isna()]

,des,orbit_id,jd,cd,dist,dist_min,dist_max,v_rel,v_inf,t_sigma_f,h,diameter,diameter_sigma,fullname
1897,289P,K192/12,2.422301e+06,1919-Dec-08 13:17,0.047236,0.047222,0.047299,11.409115,11.404170,10:47,NaN,NaN,NaN,289P/Blanpain
2649,7P,33,2.425058e+06,1927-Jun-26 19:36,0.039379,0.039379,0.039380,13.905623,13.900756,< 00:01,NaN,5.2,NaN,7P/Pons-Winnecke
4951,322P,10,2.432287e+06,1947-Apr-11 04:00,0.047438,0.046433,0.049326,40.463181,40.461793,02:19,NaN,NaN,NaN,322P/SOHO
8653,2024 OC2,8,2.441897e+06,1973-Aug-02 20:39,0.047996,0.044206,0.053939,21.711230,21.708673,18:08,NaN,NaN,NaN,P/2024 OC2 (PANSTARRS)
12276,1999 J6,9,2.451342e+06,1999-Jun-12 05:23,0.011956,0.002386,0.022134,42.918833,42.913640,05:55,NaN,NaN,NaN,P/1999 J6 (SOHO)
13075,289P,K192/12,2.452986e+06,2003-Dec-12 01:45,0.025040,0.025018,0.025063,9.046622,9.034853,00:18,NaN,NaN,NaN,289P/Blanpain
18075,252P,K212/2,2.457469e+06,2016-Mar-21 13:16,0.035634,0.035633,0.035635,10.560618,10.553535,< 00:01,NaN,NaN,NaN,252P/LINEAR
18078,460P,60,2.457470e+06,2016-Mar-22 15:31,0.023665,0.023665,0.023665,14.012553,14.004516,< 00:01,NaN,NaN,NaN,460P/PANSTARRS
37348,15P,K213/18,2.473755e+06,2060-Oct-22 17:23,0.033433,0.033418,0.033449,12.551311,12.544959,00:11,NaN,NaN,NaN,15P/Finlay
43961,73P-B,K061/24,2.491557e+06,2109-Jul-20 21:44,0.035592,0.034722,0.036463,11.951036,11.944771,01:35,NaN,NaN,NaN,73P/Schwassmann-Wachmann 3-B

### Check if any row is fully duplicated,

In [8]:
df.duplicated().sum()

np.int64(0)

### Values that are technically present but look wrong:

In [9]:
df[['dist', 'v_rel', 'v_inf', 'h']].describe()

               dist         v_rel         v_inf             h
count  51122.000000  51122.000000  51097.000000  51112.000000
mean       0.027387     10.301089     10.274646     25.219717
std        0.013987      5.271150      5.279136      2.549173
min        0.000044      0.073451      0.125474     14.080000
25%        0.015927      6.574564      6.543646     23.930000
50%        0.028381      9.313345      9.286082     25.600000
75%        0.039425     12.999827     12.976221     26.900000
max        0.050000     42.918833     42.913640     34.060000

In [10]:
df['t_sigma_f'].unique()[:30]

<StringArray>
[  '00:02',   '00:18',   '00:05',   '21:33', '4_11:16',   '00:03',   '00:34',
   '14:49', '3_02:30',   '00:31', '< 00:01', '9_08:41', '3_20:52', '5_06:04',
 '6_06:31',   '17:21', '2_05:33', '8_13:42',   '01:15', '8_00:04',   '02:46',
 '3_06:39', '4_01:16',   '02:26',   '23:01', '3_04:03',   '18:52', '5_21:15',
   '14:28', '1_13:17']
Length: 30, dtype: str

## Saw the pattern in missing h values. 
### all of them are commets

In [11]:
df[df['des'].astype('str').str.contains('P/') | df['fullname'].str.contains('P/', na=False)]

,des,orbit_id,jd,cd,dist,dist_min,dist_max,v_rel,v_inf,t_sigma_f,h,diameter,diameter_sigma,fullname
1897,289P,K192/12,2.422301e+06,1919-Dec-08 13:17,0.047236,0.047222,0.047299,11.409115,11.404170,10:47,NaN,NaN,NaN,289P/Blanpain
2649,7P,33,2.425058e+06,1927-Jun-26 19:36,0.039379,0.039379,0.039380,13.905623,13.900756,< 00:01,NaN,5.2,NaN,7P/Pons-Winnecke
4951,322P,10,2.432287e+06,1947-Apr-11 04:00,0.047438,0.046433,0.049326,40.463181,40.461793,02:19,NaN,NaN,NaN,322P/SOHO
8653,2024 OC2,8,2.441897e+06,1973-Aug-02 20:39,0.047996,0.044206,0.053939,21.711230,21.708673,18:08,NaN,NaN,NaN,P/2024 OC2 (PANSTARRS)
12276,1999 J6,9,2.451342e+06,1999-Jun-12 05:23,0.011956,0.002386,0.022134,42.918833,42.913640,05:55,NaN,NaN,NaN,P/1999 J6 (SOHO)
13075,289P,K192/12,2.452986e+06,2003-Dec-12 01:45,0.025040,0.025018,0.025063,9.046622,9.034853,00:18,NaN,NaN,NaN,289P/Blanpain
18075,252P,K212/2,2.457469e+06,2016-Mar-21 13:16,0.035634,0.035633,0.035635,10.560618,10.553535,< 00:01,NaN,NaN,NaN,252P/LINEAR
18078,460P,60,2.457470e+06,2016-Mar-22 15:31,0.023665,0.023665,0.023665,14.012553,14.004516,< 00:01,NaN,NaN,NaN,460P/PANSTARRS
37348,15P,K213/18,2.473755e+06,2060-Oct-22 17:23,0.033433,0.033418,0.033449,12.551311,12.544959,00:11,NaN,NaN,NaN,15P/Finlay
43961,73P-B,K061/24,2.491557e+06,2109-Jul-20 21:44,0.035592,0.034722,0.036463,11.951036,11.944771,01:35,NaN,NaN,NaN,73P/Schwassmann-Wachmann 3-B